marklogic-community/smart-mastering-core

src/main/ml-modules/ext/com.marklogic.smart-mastering/survivorship/merging/base.xqy

Ryan made a change to the libraries in the agile mastering repo; bringing them in here as well.

bringing in Ryan Dew's change from the AMT repo

---

src/main/ml-modules/ext/com.marklogic.smart-mastering/matcher.xqy
src/main/ml-modules/services/sm-notifications.xqy
src/test/ml-modules/root/test/suites/matching/get-notifications.xqy
src/test/ml-modules/root/test/suites/matching/teardown.xqy

Sample return value:
```
[
{
"meta":{"dateTime":"2018-04-19T20:08:22.224088Z", "user":"admin"}, 
"thresholdLabel":"Definitive Match", 
"uris":[{"uri":"/content1.xml"}, {"uri":"/content2.xml"}]
}, 
{
"meta":{"dateTime":"2018-04-19T20:08:22.221025Z", "user":"admin"}, 
"thresholdLabel":"Likely Match", 
"uris":[{"uri":"/content1.xml"}, {"uri":"/content2.xml"}, {"uri":"/content3.xml"}]
},
{
"meta":{"dateTime":"2018-04-19T20:08:22.221025Z", "user":"admin"}, 
"thresholdLabel":"Possible Match", 
"uris":[{"uri":"/content4.xml"}, {"uri":"/content5.xml"}]
}
]
```
URIs are objects because I'm intending to attach the scores to them eventually.

Notification service

---

src/main/ml-modules/ext/com.marklogic.smart-mastering/matcher.xqy
src/main/ml-modules/services/sm-notifications.xqy
src/test/ml-modules/root/test/suites/notifications/delete-notification.xqy
src/test/ml-modules/root/test/suites/notifications/lib/lib.xqy
src/test/ml-modules/root/test/suites/notifications/notifications-to-json.sjs

- When retrieving notifications, include the URI
- Delete by specifying the URI

Revise notfications

---

src/main/ml-config/databases/content-database.json
src/main/ml-config/databases/schemas-database.json
src/main/ml-modules/ext/com.marklogic.smart-mastering/impl/process.xqy
src/main/ml-modules/ext/com.marklogic.smart-mastering/impl/sm-es-impl.xqy
src/main/ml-modules/ext/com.marklogic.smart-mastering/process-records.xqy
src/main/ml-modules/ext/com.marklogic.smart-mastering/sm-entity-services.xqy
src/test/ml-modules/root/test/suites/entity-services/entity-services.sjs
src/test/ml-modules/root/test/suites/entity-services/suiteSetup.sjs
src/test/ml-modules/root/test/suites/entity-services/suiteTeardown.sjs
src/test/ml-modules/root/test/suites/entity-services/test-data/PersonNameType.entity.json

- added schemas database to configuration
- refactored process-records functionality into the impl directory

Refactoring

---

src/main/ml-modules/ext/com.marklogic.smart-mastering/auditing/base.xqy
src/test/ml-modules/root/test/suites/auditing/document-history.sjs
src/test/ml-modules/root/test/suites/auditing/history-single-merge.sjs
src/test/ml-modules/root/test/suites/auditing/lib/lib.xqy
src/test/ml-modules/root/test/suites/auditing/remerge.sjs
src/test/ml-modules/root/test/suites/auditing/setup.xqy
src/test/ml-modules/root/test/suites/auditing/test-data/doc3.xml
src/test/ml-modules/root/test/suites/auditing/test-data/doc4.xml

Limit a document's history report to the actions that it was involved in.

History bug

---

src/main/ml-modules/ext/com.marklogic.smart-mastering/matcher.xqy

throwing in some more function-level comments

adding function-level comments

---

src/test/ml-modules/root/test/suites/matching/find-document-matches-by-options-name.xqy
src/test/ml-modules/root/test/suites/matching/lib/lib.xqy
src/test/ml-modules/root/test/suites/matching/test-data/doc1.json
src/test/ml-modules/root/test/suites/matching/test-data/doc2.json
src/test/ml-modules/root/test/suites/matching/test-data/doc3.json
src/test/ml-modules/root/test/suites/merging/lib/lib.xqy
src/test/ml-modules/root/test/suites/merging/test-data/doc1.json
src/test/ml-modules/root/test/suites/merging/test-data/doc2.json

it doesn't work for mixing json and xml in a merge

verifying if json works or not

---

examples/dhf-flow/build.gradle
examples/dhf-flow/user-config/security/roles/mdm-admin.json
examples/dhf-flow/user-config/security/roles/mdm-user.json
examples/triggers/build.gradle
examples/triggers/user-config/security/roles/mdm-admin.json
examples/triggers/user-config/security/roles/mdm-user.json
src/main/ml-modules/root/com.marklogic.smart-mastering/constants.xqy
src/main/ml-modules/root/com.marklogic.smart-mastering/impl/process.xqy

adding in trace and error for no configs

fixing demos

---

src/test/ml-modules/root/test/suites/merging-json/get-instances.xqy
src/test/ml-modules/root/test/suites/merging-json/test-data/doc1.json
src/test/ml-modules/root/test/suites/merging-json/test-data/doc2.json
src/test/ml-modules/root/test/suites/merging-xml/get-instances.xqy
src/test/ml-modules/root/test/suites/merging-xml/test-data/doc1.xml
src/test/ml-modules/root/test/suites/merging-xml/test-data/doc2.xml

The get-instances function needs to exclude "info".

tests for Ryan's PR

---

examples/dhf-flow/README.md
examples/dhf-flow/build.gradle
examples/dhf-flow/gradle.properties
examples/dhf-flow/user-config/security/roles/mdm-admin.json
examples/dhf-flow/user-config/security/roles/mdm-manage.json
examples/dhf-flow/user-config/security/roles/mdm-rest-admin.json
examples/dhf-flow/user-config/security/users/mdm-admin.json
examples/dhf-flow/user-config/security/users/mdm-manage.json
examples/dhf-flow/user-config/security/users/mdm-rest-admin.json
examples/dhf-flow/user-config/security/users/mdm-user.json
examples/triggers/README.md
examples/triggers/build.gradle
examples/triggers/gradle.properties
examples/triggers/user-config/security/roles/mdm-admin.json
examples/triggers/user-config/security/roles/mdm-manage.json
examples/triggers/user-config/security/roles/mdm-rest-admin.json
examples/triggers/user-config/security/users/mdm-admin.json
examples/triggers/user-config/security/users/mdm-manage.json
examples/triggers/user-config/security/users/mdm-rest-admin.json
examples/triggers/user-config/security/users/mdm-user.json

Adds roles and users to the dhf-flow and triggers projects. Still to come: updates to the documentation pages.

Mdm 339: minimal privileges for examples

---

.gitignore
src/main/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/blocks-impl.xqy
src/main/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/matcher-impl.xqy
src/main/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/notification-impl.xqy
src/main/ml-modules/root/com.marklogic.smart-mastering/matcher.xqy
src/test/ml-modules/root/test/suites/matching/allow-match.xqy
src/test/ml-modules/root/test/suites/matching/match-response.xqy
src/test/ml-modules/root/test/suites/notifications/lib/lib.xqy
src/test/ml-modules/root/test/suites/notifications/notifications-to-json.sjs
src/test/ml-modules/root/test/suites/notifications/save-match-notification.xqy

Progress on documenting the matching code. I'm adding module-level comments to explain the purpose and approach in the library, along with function-level comments documenting the individual functions and parameters.

Mdm 395: documenting the code

---

src/main/ml-modules/root/com.marklogic.smart-mastering/merging.xqy
src/main/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy
src/test/ml-modules/root/test/suites/merging-json/get-options-as-json.sjs
src/test/ml-modules/root/test/suites/merging-json/json-options-round-trip.xqy
src/test/ml-modules/root/test/suites/merging-json/test-data/merge-options.json
src/test/ml-modules/root/test/suites/merging-json/test-data/merge-options.xml
src/test/ml-modules/root/test/suites/merging-xml/custom-sjs-action.xqy

Specific problem: when converting from XML to JSON, the merging element was turned into an object instead of an array, so we only got one of the merge elements converted.

Fix options as json

---

_data/sidenav.yml
_layouts/inner.html
_pages/docs/custom-action.md
_pages/docs/custom-match.md
_pages/docs/custom-merge.md
_pages/docs/matching-options.md
_pages/docs/merging-options.md
_pages/troubleshooting.md

- documents function signatures for custom matching, merging, and actions
- first entry on a troubleshooting page

MDM-492: documenting custom function signatures

---

src/test/ml-modules/root/test/suites/matching/match-with-posted-options.sjs

Pass the includeMatches parameter and test both true and false values.

MDM-528 Enhance unit test to verfiy includeMatches option works

---

_data/sidenav.yml
_pages/docs/docs.md
_pages/docs/error-codes.md

Creating documentation page for standard errors that can be encountered while using Smart Mastering.

MDM-486 Add Smart Mastering Error codes to docs

---

_pages/how-to-use.md

MDM-552 GH #177 Fix outdated link in documentation

---

_pages/docs/merging-options.md

Update the docs for merge options to show the latest merge capabilities added. Note that the release of the documentation should be timed with the next release from develop.

MDM-544 Update docs to show an example of merge strategies

---

_pages/docs/merging-options.md
_pages/how-does-it-work.md

Also, clarification that you must have sources to use timestamps.

Mdm 541: documentation about custom algorithms

---

src/main/ml-modules/root/com.marklogic.smart-mastering/impl/process.xqy
src/main/ml-modules/root/com.marklogic.smart-mastering/matcher.xqy
src/main/ml-modules/root/com.marklogic.smart-mastering/process-records.xqy
src/main/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy
src/test/ml-modules/root/test/suites/match-and-merge/consolidate-merges.xqy
src/test/ml-modules/root/test/suites/match-and-merge/consolidate-notifies.xqy
src/test/ml-modules/root/test/suites/match-and-merge/duplicate-no-filter.xqy
src/test/ml-modules/root/test/suites/merge-double-notify/double-notify.xqy
src/test/ml-modules/root/test/suites/merging-json/rollback-merge.xqy
src/test/ml-modules/root/test/suites/merging-xml/custom-xqy-action.xqy
src/test/ml-modules/root/test/suites/merging-xml/test-data/custom-action-xqy.xqy

Setting up PR for review, but won't merge yet. Need some changes in DHF first.

Mdm 516: pass multiple URIs into process-match-and-merge

---

src/main/ml-modules/root/com.marklogic.smart-mastering/survivorship/merging/base.xqy

Allow headers to be handled with default merge strategy

---

src/main/ml-modules/root/com.marklogic.smart-mastering/impl/process.xqy

making max-scan consistent for all uses. 
